### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'dnn_superres'

### ISSUE THREAD

**Issue by zerorail** [mehrdad-dev/Image-Upscaler-Deep-Learning#1]
Hello 

i have got this error when i opened the localhost link in my browser

> 2023-03-14 09:40:16.314 Uncaught app exception
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "G:\Image-Upscaler-Deep-Learning\streamlit_app.py", line 8, in <module>
    sr = cv2.dnn_superres.DnnSuperResImpl_create()
AttributeError: module 'cv2' has no attribute 'dnn_superres'

**Comment by mehrdad-dev** [comment]
Hey!
See this link: https://stackoverflow.com/questions/64763274/module-cv2-cv2-has-no-attribute-dnn-superres
It is about a package that you need to install, called "opencv-contrib-python".
Install it like this: `` pip uninstall opencv-contrib-python``

And tell me if your issue is resolved!
